name: travel-blog-service
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Build and test
        run: ./gradlew clean build